# Migrate gl::GL_* shim constants to typed namespaces (cap::, prim::, blend::, etc.).
$ErrorActionPreference = "Stop"
$root = Join-Path $PSScriptRoot "src"
$files = Get-ChildItem -Path $root -Recurse -Include *.cpp,*.hpp | Where-Object {
  $_.FullName -notmatch "\\build-omega\\"
}

# Longest token first to avoid partial matches (especially GL_ONE vs GL_ONE_MINUS_*).
$replacements = @(
  @("gl::GL_ONE_MINUS_SRC_ALPHA", "gl::blend::OneMinusSrcAlpha"),
  @("client::gl::GL_ONE_MINUS_SRC_ALPHA", "client::gl::blend::OneMinusSrcAlpha"),
  @("gl::GL_ONE_MINUS_SRC_COLOR", "gl::blend::OneMinusSrcColor"),
  @("client::gl::GL_ONE_MINUS_SRC_COLOR", "client::gl::blend::OneMinusSrcColor"),
  @("gl::GL_ONE_MINUS_DST_COLOR", "gl::blend::OneMinusDstColor"),
  @("client::gl::GL_ONE_MINUS_DST_COLOR", "client::gl::blend::OneMinusDstColor"),
  @("gl::GL_NEAREST_MIPMAP_LINEAR", "gl::filter::NearestMipmapLinear"),
  @("client::gl::GL_NEAREST_MIPMAP_LINEAR", "client::gl::filter::NearestMipmapLinear"),
  @("gl::GL_LINEAR_MIPMAP_LINEAR", "gl::filter::LinearMipmapLinear"),
  @("client::gl::GL_LINEAR_MIPMAP_LINEAR", "client::gl::filter::LinearMipmapLinear"),
  @("gl::GL_AMBIENT_AND_DIFFUSE", "gl::light::AmbientAndDiffuse"),
  @("client::gl::GL_AMBIENT_AND_DIFFUSE", "client::gl::light::AmbientAndDiffuse"),
  @("gl::GL_LIGHT_MODEL_AMBIENT", "gl::light::LightModelAmbient"),
  @("client::gl::GL_LIGHT_MODEL_AMBIENT", "client::gl::light::LightModelAmbient"),
  @("gl::GL_TEXTURE_COORD_ARRAY", "gl::client_array::TextureCoordArray"),
  @("client::gl::GL_TEXTURE_COORD_ARRAY", "client::gl::client_array::TextureCoordArray"),
  @("gl::GL_TEXTURE_BINDING_2D", "gl::tex::Binding2D"),
  @("client::gl::GL_TEXTURE_BINDING_2D", "client::gl::tex::Binding2D"),
  @("gl::GL_TEXTURE_MIN_FILTER", "gl::tex::MinFilter"),
  @("client::gl::GL_TEXTURE_MIN_FILTER", "client::gl::tex::MinFilter"),
  @("gl::GL_TEXTURE_MAG_FILTER", "gl::tex::MagFilter"),
  @("client::gl::GL_TEXTURE_MAG_FILTER", "client::gl::tex::MagFilter"),
  @("gl::GL_TEXTURE_WRAP_S", "gl::tex::WrapS"),
  @("client::gl::GL_TEXTURE_WRAP_S", "client::gl::tex::WrapS"),
  @("gl::GL_TEXTURE_WRAP_T", "gl::tex::WrapT"),
  @("client::gl::GL_TEXTURE_WRAP_T", "client::gl::tex::WrapT"),
  @("gl::GL_MODELVIEW_MATRIX", "gl::matrix_::ModelViewMatrix"),
  @("client::gl::GL_MODELVIEW_MATRIX", "client::gl::matrix_::ModelViewMatrix"),
  @("gl::GL_PROJECTION_MATRIX", "gl::matrix_::ProjectionMatrix"),
  @("client::gl::GL_PROJECTION_MATRIX", "client::gl::matrix_::ProjectionMatrix"),
  @("gl::GL_COLOR_BUFFER_BIT", "gl::attrib::ColorBufferBit"),
  @("client::gl::GL_COLOR_BUFFER_BIT", "client::gl::attrib::ColorBufferBit"),
  @("gl::GL_DEPTH_BUFFER_BIT", "gl::attrib::DepthBufferBit"),
  @("client::gl::GL_DEPTH_BUFFER_BIT", "client::gl::attrib::DepthBufferBit"),
  @("gl::GL_POLYGON_OFFSET_FILL", "gl::cap::PolygonOffsetFill"),
  @("client::gl::GL_POLYGON_OFFSET_FILL", "client::gl::cap::PolygonOffsetFill"),
  @("gl::GL_RESCALE_NORMAL", "gl::cap::RescaleNormal"),
  @("client::gl::GL_RESCALE_NORMAL", "client::gl::cap::RescaleNormal"),
  @("gl::GL_COLOR_MATERIAL", "gl::cap::ColorMaterial"),
  @("client::gl::GL_COLOR_MATERIAL", "client::gl::cap::ColorMaterial"),
  @("gl::GL_SCISSOR_TEST", "gl::cap::ScissorTest"),
  @("client::gl::GL_SCISSOR_TEST", "client::gl::cap::ScissorTest"),
  @("gl::GL_TRIANGLE_FAN", "gl::prim::TriangleFan"),
  @("client::gl::GL_TRIANGLE_FAN", "client::gl::prim::TriangleFan"),
  @("gl::GL_LINE_STRIP", "gl::prim::LineStrip"),
  @("client::gl::GL_LINE_STRIP", "client::gl::prim::LineStrip"),
  @("gl::GL_LINE_LOOP", "gl::prim::LineLoop"),
  @("client::gl::GL_LINE_LOOP", "client::gl::prim::LineLoop"),
  @("gl::GL_QUAD_STRIP", "gl::prim::QuadStrip"),
  @("client::gl::GL_QUAD_STRIP", "client::gl::prim::QuadStrip"),
  @("gl::GL_TRIANGLES", "gl::prim::Triangles"),
  @("client::gl::GL_TRIANGLES", "client::gl::prim::Triangles"),
  @("gl::GL_UNSIGNED_BYTE", "gl::pixel::UnsignedByte"),
  @("client::gl::GL_UNSIGNED_BYTE", "client::gl::pixel::UnsignedByte"),
  @("gl::GL_CURRENT_COLOR", "gl::query::CurrentColor"),
  @("client::gl::GL_CURRENT_COLOR", "client::gl::query::CurrentColor"),
  @("gl::GL_TEXTURE_2D", "gl::cap::Texture2D"),
  @("client::gl::GL_TEXTURE_2D", "client::gl::cap::Texture2D"),
  @("gl::GL_ALPHA_TEST", "gl::cap::AlphaTest"),
  @("client::gl::GL_ALPHA_TEST", "client::gl::cap::AlphaTest"),
  @("gl::GL_DEPTH_TEST", "gl::cap::DepthTest"),
  @("client::gl::GL_DEPTH_TEST", "client::gl::cap::DepthTest"),
  @("gl::GL_CULL_FACE", "gl::cap::CullFace"),
  @("client::gl::GL_CULL_FACE", "client::gl::cap::CullFace"),
  @("gl::GL_LIGHTING", "gl::cap::Lighting"),
  @("client::gl::GL_LIGHTING", "client::gl::cap::Lighting"),
  @("gl::GL_NORMALIZE", "gl::cap::Normalize"),
  @("client::gl::GL_NORMALIZE", "client::gl::cap::Normalize"),
  @("gl::GL_SRC_ALPHA", "gl::blend::SrcAlpha"),
  @("client::gl::GL_SRC_ALPHA", "client::gl::blend::SrcAlpha"),
  @("gl::GL_SRC_COLOR", "gl::blend::SrcColor"),
  @("client::gl::GL_SRC_COLOR", "client::gl::blend::SrcColor"),
  @("gl::GL_DST_COLOR", "gl::blend::DstColor"),
  @("client::gl::GL_DST_COLOR", "client::gl::blend::DstColor"),
  @("gl::GL_DST_ALPHA", "gl::blend::DstAlpha"),
  @("client::gl::GL_DST_ALPHA", "client::gl::blend::DstAlpha"),
  @("gl::GL_MODELVIEW", "gl::matrix_::ModelView"),
  @("client::gl::GL_MODELVIEW", "client::gl::matrix_::ModelView"),
  @("gl::GL_PROJECTION", "gl::matrix_::Projection"),
  @("client::gl::GL_PROJECTION", "client::gl::matrix_::Projection"),
  @("gl::GL_VERTEX_ARRAY", "gl::client_array::VertexArray"),
  @("client::gl::GL_VERTEX_ARRAY", "client::gl::client_array::VertexArray"),
  @("gl::GL_NORMAL_ARRAY", "gl::client_array::NormalArray"),
  @("client::gl::GL_NORMAL_ARRAY", "client::gl::client_array::NormalArray"),
  @("gl::GL_COLOR_ARRAY", "gl::client_array::ColorArray"),
  @("client::gl::GL_COLOR_ARRAY", "client::gl::client_array::ColorArray"),
  @("gl::GL_FOG_COLOR", "gl::fog::Color"),
  @("client::gl::GL_FOG_COLOR", "client::gl::fog::Color"),
  @("gl::GL_FOG_MODE", "gl::fog::Mode"),
  @("client::gl::GL_FOG_MODE", "client::gl::fog::Mode"),
  @("gl::GL_FOG_DENSITY", "gl::fog::Density"),
  @("client::gl::GL_FOG_DENSITY", "client::gl::fog::Density"),
  @("gl::GL_FOG_START", "gl::fog::Start"),
  @("client::gl::GL_FOG_START", "client::gl::fog::Start"),
  @("gl::GL_FOG_END", "gl::fog::End"),
  @("client::gl::GL_FOG_END", "client::gl::fog::End"),
  @("gl::GL_GEQUAL", "gl::compare::Gequal"),
  @("client::gl::GL_GEQUAL", "client::gl::compare::Gequal"),
  @("gl::GL_LEQUAL", "gl::compare::Lequal"),
  @("client::gl::GL_LEQUAL", "client::gl::compare::Lequal"),
  @("gl::GL_GREATER", "gl::compare::Greater"),
  @("client::gl::GL_GREATER", "client::gl::compare::Greater"),
  @("gl::GL_EQUAL", "gl::compare::Equal"),
  @("client::gl::GL_EQUAL", "client::gl::compare::Equal"),
  @("gl::GL_SMOOTH", "gl::shade::Smooth"),
  @("client::gl::GL_SMOOTH", "client::gl::shade::Smooth"),
  @("gl::GL_QUADS", "gl::prim::Quads"),
  @("client::gl::GL_QUADS", "client::gl::prim::Quads"),
  @("gl::GL_LINES", "gl::prim::Lines"),
  @("client::gl::GL_LINES", "client::gl::prim::Lines"),
  @("gl::GL_POINTS", "gl::prim::Points"),
  @("client::gl::GL_POINTS", "client::gl::prim::Points"),
  @("gl::GL_FLOAT", "gl::pixel::Float"),
  @("client::gl::GL_FLOAT", "client::gl::pixel::Float"),
  @("gl::GL_BYTE", "gl::pixel::Byte"),
  @("client::gl::GL_BYTE", "client::gl::pixel::Byte"),
  @("gl::GL_DOUBLE", "gl::pixel::Double"),
  @("client::gl::GL_DOUBLE", "client::gl::pixel::Double"),
  @("gl::GL_RGBA", "gl::pixel::Rgba"),
  @("client::gl::GL_RGBA", "client::gl::pixel::Rgba"),
  @("gl::GL_CLAMP", "gl::wrap::Clamp"),
  @("client::gl::GL_CLAMP", "client::gl::wrap::Clamp"),
  @("gl::GL_REPEAT", "gl::wrap::Repeat"),
  @("client::gl::GL_REPEAT", "client::gl::wrap::Repeat"),
  @("gl::GL_NEAREST", "gl::filter::Nearest"),
  @("client::gl::GL_NEAREST", "client::gl::filter::Nearest"),
  @("gl::GL_LINEAR", "gl::filter::Linear"),
  @("client::gl::GL_LINEAR", "client::gl::filter::Linear"),
  @("gl::GL_TEXTURE0", "gl::tex::Texture0"),
  @("client::gl::GL_TEXTURE0", "client::gl::tex::Texture0"),
  @("gl::GL_LIGHT0", "gl::light::Light0"),
  @("client::gl::GL_LIGHT0", "client::gl::light::Light0"),
  @("gl::GL_LIGHT1", "gl::light::Light1"),
  @("client::gl::GL_LIGHT1", "client::gl::light::Light1"),
  @("gl::GL_POSITION", "gl::light::Position"),
  @("client::gl::GL_POSITION", "client::gl::light::Position"),
  @("gl::GL_DIFFUSE", "gl::light::Diffuse"),
  @("client::gl::GL_DIFFUSE", "client::gl::light::Diffuse"),
  @("gl::GL_SPECULAR", "gl::light::Specular"),
  @("client::gl::GL_SPECULAR", "client::gl::light::Specular"),
  @("gl::GL_AMBIENT", "gl::light::Ambient"),
  @("client::gl::GL_AMBIENT", "client::gl::light::Ambient"),
  @("gl::GL_BLEND", "gl::cap::Blend"),
  @("client::gl::GL_BLEND", "client::gl::cap::Blend"),
  @("gl::GL_FOG", "gl::cap::Fog"),
  @("client::gl::GL_FOG", "client::gl::cap::Fog"),
  @("gl::GL_FLAT", "gl::shade::Flat"),
  @("client::gl::GL_FLAT", "client::gl::shade::Flat"),
  @("gl::GL_BACK", "gl::face::Back"),
  @("client::gl::GL_BACK", "client::gl::face::Back"),
  @("gl::GL_FRONT", "gl::face::Front"),
  @("client::gl::GL_FRONT", "client::gl::face::Front"),
  @("gl::GL_ONE", "gl::blend::One"),
  @("client::gl::GL_ONE", "client::gl::blend::One"),
  @("gl::GL_ZERO", "gl::blend::Zero"),
  @("client::gl::GL_ZERO", "client::gl::blend::Zero"),
  @("gl::GL_VIEWPORT", "gl::query::Viewport"),
  @("client::gl::GL_VIEWPORT", "client::gl::query::Viewport"),
  @("gl::isolate::", "gl::preset::"),
  @("client::gl::isolate::", "client::gl::preset::")
)

foreach($file in $files) {
  $text = [IO.File]::ReadAllText($file.FullName)
  $orig = $text
  foreach($pair in $replacements) {
    $text = $text.Replace($pair[0], $pair[1])
  }
  if($text -ne $orig) {
    [IO.File]::WriteAllText($file.FullName, $text)
    Write-Host "Updated $($file.FullName)"
  }
}

Write-Host "GL typed constant refactor complete."
