local settings = require("lib.settings")

local config = settings.define("item_drop_physics", {
  name = "Item Drop Physics",
  fields = {
    gravity = {
      type = "slider",
      label = "Gravity (blocks/s²)",
      min = -32,
      max = -0.1,
      step = 0.1,
      default = -16.0,
    },
    max_speed = {
      type = "slider",
      label = "Max Speed (blocks/s)",
      min = 1,
      max = 20,
      step = 0.1,
      default = 12.0,
    },
    max_spin = {
      type = "slider",
      label = "Max Spin (rad/s)",
      min = 1,
      max = 30,
      step = 0.1,
      default = 14.0,
    },
    bounce_cutoff = {
      type = "slider",
      label = "Bounce Cutoff (blocks/s)",
      min = 0.1,
      max = 5,
      step = 0.05,
      default = 1.2,
    },
    water_drag = {
      type = "slider",
      label = "Water Drag (per-tick)",
      min = 0.1,
      max = 0.99,
      step = 0.01,
      default = 0.80,
    },
    flow_accel = {
      type = "slider",
      label = "Water Flow Acceleration (blocks/s²)",
      min = 0.1,
      max = 10,
      step = 0.1,
      default = 4.0,
    },
    draw_scale = {
      type = "slider",
      label = "Draw Scale",
      min = 0.1,
      max = 1.0,
      step = 0.05,
      default = 0.25,
    },
    max_substeps = {
      type = "int",
      label = "Max Substeps",
      min = 1,
      max = 8,
      default = 4,
    },
    sleep_ticks = {
      type = "int",
      label = "Sleep Ticks",
      min = 1,
      max = 60,
      default = 12,
    },
    buoyancy_clamp = {
      type = "slider",
      label = "Buoyancy Clamp",
      min = 0.1,
      max = 5,
      step = 0.1,
      default = 2.5,
    },
    sleep_speed = {
      type = "slider",
      label = "Sleep Speed Threshold (blocks/s)",
      min = 0.001,
      max = 0.2,
      step = 0.001,
      default = 0.02,
    },
    sleep_spin = {
      type = "slider",
      label = "Sleep Spin Threshold (rad/s)",
      min = 0.01,
      max = 1.0,
      step = 0.01,
      default = 0.10,
    },
  },
})

return config
