#pragma once
// GLCore - VBO and multi-texture entry points for fixed-function rendering.
#include <windows.h>
#include <GL/gl.h>
#include <cstdint>
namespace net::minecraft::client::gl {
using PFN_GenBuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindBuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_BufferData = void(APIENTRY*)(unsigned, intptr_t, const void*, unsigned);
using PFN_BufferSubData = void(APIENTRY*)(unsigned, intptr_t, intptr_t, const void*);
using PFN_DeleteBuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_SwapInterval = void(APIENTRY*)(int);
using PFN_GenFramebuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindFramebuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_DeleteFramebuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_CheckFramebufferStatus = unsigned(APIENTRY*)(unsigned);
using PFN_FramebufferTexture2D = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned, int);
using PFN_GenRenderbuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindRenderbuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_DeleteRenderbuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_RenderbufferStorage = void(APIENTRY*)(unsigned, unsigned, int, int);
using PFN_FramebufferRenderbuffer = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned);
using PFN_DrawBuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_MultiDrawArrays = void(APIENTRY*)(unsigned, const int*, const int*, int);
using PFN_CreateShader = unsigned int(APIENTRY*)(unsigned int);
using PFN_ShaderSource = void(APIENTRY*)(unsigned int, int, const char* const*, const int*);
using PFN_CompileShader = void(APIENTRY*)(unsigned int);
using PFN_GetShaderiv = void(APIENTRY*)(unsigned int, unsigned int, int*);
using PFN_GetShaderInfoLog = void(APIENTRY*)(unsigned int, int, int*, char*);
using PFN_CreateProgram = unsigned int(APIENTRY*)();
using PFN_AttachShader = void(APIENTRY*)(unsigned int, unsigned int);
using PFN_LinkProgram = void(APIENTRY*)(unsigned int);
using PFN_GetProgramiv = void(APIENTRY*)(unsigned int, unsigned int, int*);
using PFN_GetProgramInfoLog = void(APIENTRY*)(unsigned int, int, int*, char*);
using PFN_UseProgram = void(APIENTRY*)(unsigned int);
using PFN_DeleteShader = void(APIENTRY*)(unsigned int);
using PFN_DeleteProgram = void(APIENTRY*)(unsigned int);
using PFN_GetUniformLocation = int(APIENTRY*)(unsigned int, const char*);
using PFN_GetActiveUniform = void(APIENTRY*)(unsigned int, unsigned int, int, int*, int*, unsigned int*, char*);
using PFN_Uniform1f = void(APIENTRY*)(int, float);
using PFN_Uniform2f = void(APIENTRY*)(int, float, float);
using PFN_Uniform3f = void(APIENTRY*)(int, float, float, float);
using PFN_Uniform4f = void(APIENTRY*)(int, float, float, float, float);
using PFN_Uniform1i = void(APIENTRY*)(int, int);
using PFN_Uniform2i = void(APIENTRY*)(int, int, int);
using PFN_Uniform3i = void(APIENTRY*)(int, int, int, int);
using PFN_Uniform4i = void(APIENTRY*)(int, int, int, int, int);
// Core-profile plumbing (loaded in Phase A; wired up in Phase B/C).
using PFN_UniformMatrix4fv = void(APIENTRY*)(int, int, unsigned char, const float*);
using PFN_GetAttribLocation = int(APIENTRY*)(unsigned, const char*);
using PFN_BindAttribLocation = void(APIENTRY*)(unsigned, unsigned, const char*);
using PFN_GenVertexArrays = void(APIENTRY*)(int, unsigned*);
using PFN_BindVertexArray = void(APIENTRY*)(unsigned);
using PFN_DeleteVertexArrays = void(APIENTRY*)(int, const unsigned*);
using PFN_VertexAttribPointer = void(APIENTRY*)(unsigned, int, unsigned, unsigned char, int, const void*);
using PFN_EnableVertexAttribArray = void(APIENTRY*)(unsigned);
using PFN_DisableVertexAttribArray = void(APIENTRY*)(unsigned);
using PFN_VertexAttrib4f = void(APIENTRY*)(unsigned, float, float, float, float);
using PFN_BindBufferRange = void(APIENTRY*)(unsigned, unsigned, unsigned, intptr_t, intptr_t);
using PFN_GenerateMipmap = void(APIENTRY*)(unsigned);
using PFN_GetStringi = const unsigned char*(APIENTRY*)(unsigned, unsigned);
using PFN_DebugProc = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned, int, const char*, const void*);
using PFN_DebugMessageCallback = void(APIENTRY*)(PFN_DebugProc, const void*);
using PFN_BlitFramebuffer =
    void(APIENTRY*)(int, int, int, int, int, int, int, int, unsigned, unsigned);
using PFN_MapBufferRange = void*(APIENTRY*)(unsigned, intptr_t, intptr_t, unsigned);
using PFN_UnmapBuffer = unsigned char(APIENTRY*)(unsigned);
using PFN_FlushMappedBufferRange = void(APIENTRY*)(unsigned, intptr_t, intptr_t);
using PFN_TexImage3D = void(APIENTRY*)(unsigned, int, int, int, int, int, int, unsigned, unsigned, const void*);
using PFN_TexSubImage3D =
    void(APIENTRY*)(unsigned, int, int, int, int, int, int, int, unsigned, unsigned, const void*);
using PFN_GenQueries = void(APIENTRY*)(int, unsigned*);
using PFN_DeleteQueries = void(APIENTRY*)(int, const unsigned*);
using PFN_BeginQuery = void(APIENTRY*)(unsigned, unsigned);
using PFN_EndQuery = void(APIENTRY*)(unsigned);
using PFN_GetQueryObjectiv = void(APIENTRY*)(unsigned, unsigned, int*);
using PFN_GetQueryObjectui64v = void(APIENTRY*)(unsigned, unsigned, std::uint64_t*);
struct GLCore {
 static PFN_GenBuffers genBuffers;
 static PFN_BindBuffer bindBuffer;
 static PFN_BufferData bufferData;
 static PFN_BufferSubData bufferSubData;
 static PFN_DeleteBuffers deleteBuffers;
 static PFN_SwapInterval swapInterval;
 static PFN_GenFramebuffers genFramebuffers;
 static PFN_BindFramebuffer bindFramebuffer;
 static PFN_DeleteFramebuffers deleteFramebuffers;
 static PFN_CheckFramebufferStatus checkFramebufferStatus;
 static PFN_FramebufferTexture2D framebufferTexture2D;
 static PFN_GenRenderbuffers genRenderbuffers;
 static PFN_BindRenderbuffer bindRenderbuffer;
 static PFN_DeleteRenderbuffers deleteRenderbuffers;
 static PFN_RenderbufferStorage renderbufferStorage;
 static PFN_FramebufferRenderbuffer framebufferRenderbuffer;
 static PFN_DrawBuffers drawBuffers;
 static PFN_MultiDrawArrays multiDrawArrays;
 static PFN_CreateShader createShader;
 static PFN_ShaderSource shaderSource;
 static PFN_CompileShader compileShader;
 static PFN_GetShaderiv getShaderiv;
 static PFN_GetShaderInfoLog getShaderInfoLog;
 static PFN_CreateProgram createProgram;
 static PFN_AttachShader attachShader;
 static PFN_LinkProgram linkProgram;
 static PFN_GetProgramiv getProgramiv;
 static PFN_GetProgramInfoLog getProgramInfoLog;
 static PFN_UseProgram useProgram;
 static PFN_DeleteShader deleteShader;
 static PFN_DeleteProgram deleteProgram;
 static PFN_GetUniformLocation getUniformLocation;
 static PFN_GetActiveUniform getActiveUniform;
 static PFN_Uniform1f uniform1f;
 static PFN_Uniform2f uniform2f;
 static PFN_Uniform3f uniform3f;
 static PFN_Uniform4f uniform4f;
 static PFN_Uniform1i uniform1i;
 static PFN_Uniform2i uniform2i;
 static PFN_Uniform3i uniform3i;
 static PFN_Uniform4i uniform4i;
 static PFN_UniformMatrix4fv uniformMatrix4fv;
 static PFN_GetAttribLocation getAttribLocation;
 static PFN_BindAttribLocation bindAttribLocation;
 static PFN_GenVertexArrays genVertexArrays;
 static PFN_BindVertexArray bindVertexArray;
 static PFN_DeleteVertexArrays deleteVertexArrays;
 static PFN_VertexAttribPointer vertexAttribPointer;
 static PFN_EnableVertexAttribArray enableVertexAttribArray;
 static PFN_DisableVertexAttribArray disableVertexAttribArray;
 static PFN_VertexAttrib4f vertexAttrib4f;
 static PFN_BindBufferRange bindBufferRange;
 static PFN_GenerateMipmap generateMipmap;
 static PFN_GetStringi getStringi;
 static PFN_DebugMessageCallback debugMessageCallback;
 static PFN_BlitFramebuffer blitFramebuffer;
 static PFN_MapBufferRange mapBufferRange;
 static PFN_UnmapBuffer unmapBuffer;
 static PFN_FlushMappedBufferRange flushMappedBufferRange;
 static PFN_TexImage3D texImage3D;
 static PFN_TexSubImage3D texSubImage3D;
 static PFN_GenQueries genQueries;
 static PFN_DeleteQueries deleteQueries;
 static PFN_BeginQuery beginQuery;
 static PFN_EndQuery endQuery;
 static PFN_GetQueryObjectiv getQueryObjectiv;
 static PFN_GetQueryObjectui64v getQueryObjectui64v;
 static void* activeTexture;
 static bool vboSupported;
 static bool framebufferSupported;
 static bool vaoSupported;
 static bool shaderSupported;
 static bool timerQuerySupported;
 static void init();
 static void ensureLoaded();
};
} // namespace net::minecraft::client::gl
