#pragma once
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <GL/gl.h>
#include <cstdint>
namespace net::minecraft::client::gl {
using PFN_GenBuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindBuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_BufferData = void(APIENTRY*)(unsigned, intptr_t, const void*, unsigned);
using PFN_BufferSubData = void(APIENTRY*)(unsigned, intptr_t, intptr_t, const void*);
using PFN_CopyBufferSubData = void(APIENTRY*)(unsigned, unsigned, intptr_t, intptr_t, intptr_t);
using PFN_BufferStorage = void(APIENTRY*)(unsigned, intptr_t, const void*, unsigned);
using PFN_ClearBufferSubData = void(APIENTRY*)(unsigned, unsigned, intptr_t, intptr_t, unsigned, unsigned, const void*);
using PFN_MapBufferRange = void*(APIENTRY*)(unsigned, intptr_t, intptr_t, unsigned);
using PFN_UnmapBuffer = unsigned char(APIENTRY*)(unsigned);
using PFN_DeleteBuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_FenceSync = void*(APIENTRY*)(unsigned, unsigned);
using PFN_ClientWaitSync = unsigned(APIENTRY*)(void*, unsigned, std::uint64_t);
using PFN_DeleteSync = void(APIENTRY*)(void*);
using PFN_SwapInterval = void(APIENTRY*)(int);
using PFN_GenFramebuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindFramebuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_DeleteFramebuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_CheckFramebufferStatus = unsigned(APIENTRY*)(unsigned);
using PFN_FramebufferTexture2D = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned, int);
using PFN_GenRenderbuffers = void(APIENTRY*)(int, unsigned*);
using PFN_BindRenderbuffer = void(APIENTRY*)(unsigned, unsigned);
using PFN_DeleteRenderbuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_RenderbufferStorage = void(APIENTRY*)(unsigned, unsigned, int, int);
using PFN_FramebufferRenderbuffer = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned);
using PFN_DrawBuffers = void(APIENTRY*)(int, const unsigned*);
using PFN_ClearBufferfv = void(APIENTRY*)(unsigned, int, const float*);
using PFN_ClearBufferuiv = void(APIENTRY*)(unsigned, int, const unsigned*);
using PFN_ClearBufferiv = void(APIENTRY*)(unsigned, int, const int*);
using PFN_PatchParameteri = void(APIENTRY*)(unsigned, int);
using PFN_MultiDrawArrays = void(APIENTRY*)(unsigned, const int*, const int*, int);
using PFN_DrawElementsBaseVertex = void(APIENTRY*)(unsigned, int, unsigned, const void*, int);
using PFN_MultiDrawElementsBaseVertex =
    void(APIENTRY*)(unsigned, const int*, unsigned, const void* const*, int, const int*);
using PFN_DrawArraysInstanced = void(APIENTRY*)(unsigned, int, int, int);
using PFN_VertexAttribDivisor = void(APIENTRY*)(unsigned, unsigned);
using PFN_CreateShader = unsigned int(APIENTRY*)(unsigned int);
using PFN_ShaderSource = void(APIENTRY*)(unsigned int, int, const char* const*, const int*);
using PFN_CompileShader = void(APIENTRY*)(unsigned int);
using PFN_MaxShaderCompilerThreadsKHR = void(APIENTRY*)(unsigned int);
using PFN_GetShaderiv = void(APIENTRY*)(unsigned int, unsigned int, int*);
using PFN_GetShaderInfoLog = void(APIENTRY*)(unsigned int, int, int*, char*);
using PFN_CreateProgram = unsigned int(APIENTRY*)();
using PFN_AttachShader = void(APIENTRY*)(unsigned int, unsigned int);
using PFN_LinkProgram = void(APIENTRY*)(unsigned int);
using PFN_GetProgramiv = void(APIENTRY*)(unsigned int, unsigned int, int*);
using PFN_GetProgramInfoLog = void(APIENTRY*)(unsigned int, int, int*, char*);
using PFN_GetActiveUniform = void(APIENTRY*)(unsigned int, unsigned int, int, int*, int*, unsigned int*, char*);
using PFN_UseProgram = void(APIENTRY*)(unsigned int);
using PFN_DeleteShader = void(APIENTRY*)(unsigned int);
using PFN_DeleteProgram = void(APIENTRY*)(unsigned int);
using PFN_GetUniformLocation = int(APIENTRY*)(unsigned int, const char*);
using PFN_Uniform1f = void(APIENTRY*)(int, float);
using PFN_Uniform2f = void(APIENTRY*)(int, float, float);
using PFN_Uniform3f = void(APIENTRY*)(int, float, float, float);
using PFN_Uniform4f = void(APIENTRY*)(int, float, float, float, float);
using PFN_Uniform1i = void(APIENTRY*)(int, int);
using PFN_Uniform2i = void(APIENTRY*)(int, int, int);
using PFN_Uniform3i = void(APIENTRY*)(int, int, int, int);
using PFN_Uniform4i = void(APIENTRY*)(int, int, int, int, int);
using PFN_UniformMatrix3fv = void(APIENTRY*)(int, int, unsigned char, const float*);
using PFN_UniformMatrix4fv = void(APIENTRY*)(int, int, unsigned char, const float*);
using PFN_GetAttribLocation = int(APIENTRY*)(unsigned, const char*);
using PFN_BindAttribLocation = void(APIENTRY*)(unsigned, unsigned, const char*);
using PFN_GenVertexArrays = void(APIENTRY*)(int, unsigned*);
using PFN_BindVertexArray = void(APIENTRY*)(unsigned);
using PFN_DeleteVertexArrays = void(APIENTRY*)(int, const unsigned*);
using PFN_VertexAttribPointer = void(APIENTRY*)(unsigned, int, unsigned, unsigned char, int, const void*);
using PFN_VertexAttribIPointer = void(APIENTRY*)(unsigned, int, unsigned, int, const void*);
using PFN_EnableVertexAttribArray = void(APIENTRY*)(unsigned);
using PFN_DisableVertexAttribArray = void(APIENTRY*)(unsigned);
using PFN_VertexAttrib4f = void(APIENTRY*)(unsigned, float, float, float, float);
using PFN_GenerateMipmap = void(APIENTRY*)(unsigned);
using PFN_GetStringi = const unsigned char*(APIENTRY*)(unsigned, unsigned);
using PFN_BlitFramebuffer = void(APIENTRY*)(int, int, int, int, int, int, int, int, unsigned, unsigned);
using PFN_TexImage3D = void(APIENTRY*)(unsigned, int, int, int, int, int, int, unsigned, unsigned, const void*);
using PFN_GenQueries = void(APIENTRY*)(int, unsigned*);
using PFN_DeleteQueries = void(APIENTRY*)(int, const unsigned*);
using PFN_BeginQuery = void(APIENTRY*)(unsigned, unsigned);
using PFN_EndQuery = void(APIENTRY*)(unsigned);
using PFN_GetQueryObjectiv = void(APIENTRY*)(unsigned, unsigned, int*);
using PFN_GetQueryObjectui64v = void(APIENTRY*)(unsigned, unsigned, std::uint64_t*);
using PFN_QueryCounter = void(APIENTRY*)(unsigned, unsigned);
// see third_party/mcp/iris/gl/texture/DepthCopyStrategy.java Gl43CopyImage
using PFN_CopyImageSubData = void(APIENTRY*)(unsigned, unsigned, int, int, int, int,
                                             unsigned, unsigned, int, int, int, int,
                                             int, int, int);
using PFN_DispatchCompute = void(APIENTRY*)(unsigned, unsigned, unsigned);
using PFN_DispatchComputeIndirect = void(APIENTRY*)(intptr_t);
using PFN_MemoryBarrier = void(APIENTRY*)(unsigned);
using PFN_BindImageTexture =
    void(APIENTRY*)(unsigned, unsigned, int, unsigned char, int, unsigned, unsigned);
using PFN_ClearTexImage = void(APIENTRY*)(unsigned, int, unsigned, unsigned, const void*);
using PFN_BindBufferBase = void(APIENTRY*)(unsigned, unsigned, unsigned);
using PFN_GenSamplers = void(APIENTRY*)(int, unsigned*);
using PFN_DeleteSamplers = void(APIENTRY*)(int, const unsigned*);
using PFN_BindSampler = void(APIENTRY*)(unsigned, unsigned);
using PFN_SamplerParameteri = void(APIENTRY*)(unsigned, unsigned, int);
using PFN_BlendFunci = void(APIENTRY*)(unsigned, unsigned, unsigned);
using PFN_BlendFuncSeparate = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned);
using PFN_BlendFuncSeparatei = void(APIENTRY*)(unsigned, unsigned, unsigned, unsigned, unsigned);
enum class SwapPacing {
 Unlimited = 0,
 VSync = 1,
 Adaptive = 2,
};
struct GLCore {
 static PFN_GenBuffers genBuffers;
 static PFN_BindBuffer bindBuffer;
 static PFN_BufferData bufferData;
 static PFN_BufferSubData bufferSubData;
 static PFN_CopyBufferSubData copyBufferSubData;
 static PFN_BufferStorage bufferStorage;
 static PFN_ClearBufferSubData clearBufferSubData;
 static PFN_MapBufferRange mapBufferRange;
 static PFN_UnmapBuffer unmapBuffer;
 static PFN_DeleteBuffers deleteBuffers;
 static PFN_FenceSync fenceSync;
 static PFN_ClientWaitSync clientWaitSync;
 static PFN_DeleteSync deleteSync;
 static PFN_SwapInterval swapInterval;
 static PFN_GenFramebuffers genFramebuffers;
 static PFN_BindFramebuffer bindFramebuffer;
 static PFN_DeleteFramebuffers deleteFramebuffers;
 static PFN_CheckFramebufferStatus checkFramebufferStatus;
 static PFN_FramebufferTexture2D framebufferTexture2D;
 static PFN_GenRenderbuffers genRenderbuffers;
 static PFN_BindRenderbuffer bindRenderbuffer;
 static PFN_DeleteRenderbuffers deleteRenderbuffers;
 static PFN_RenderbufferStorage renderbufferStorage;
 static PFN_FramebufferRenderbuffer framebufferRenderbuffer;
 static PFN_DrawBuffers drawBuffers;
 static PFN_ClearBufferfv clearBufferfv;
 static PFN_ClearBufferuiv clearBufferuiv;
 static PFN_ClearBufferiv clearBufferiv;
 static PFN_PatchParameteri patchParameteri;
 static PFN_MultiDrawArrays multiDrawArrays;
 static PFN_DrawElementsBaseVertex drawElementsBaseVertex;
 static PFN_MultiDrawElementsBaseVertex multiDrawElementsBaseVertex;
 static PFN_DrawArraysInstanced drawArraysInstanced;
 static PFN_VertexAttribDivisor vertexAttribDivisor;
 static PFN_CreateShader createShader;
 static PFN_ShaderSource shaderSource;
 static PFN_CompileShader compileShader;
 static PFN_MaxShaderCompilerThreadsKHR maxShaderCompilerThreadsKHR;
 static PFN_GetShaderiv getShaderiv;
 static PFN_GetShaderInfoLog getShaderInfoLog;
 static PFN_CreateProgram createProgram;
 static PFN_AttachShader attachShader;
 static PFN_LinkProgram linkProgram;
 static PFN_GetProgramiv getProgramiv;
 static PFN_GetProgramInfoLog getProgramInfoLog;
 static PFN_GetActiveUniform getActiveUniform;
 static PFN_UseProgram useProgram;
 static PFN_DeleteShader deleteShader;
 static PFN_DeleteProgram deleteProgram;
 static PFN_GetUniformLocation getUniformLocation;
 static PFN_Uniform1f uniform1f;
 static PFN_Uniform2f uniform2f;
 static PFN_Uniform3f uniform3f;
 static PFN_Uniform4f uniform4f;
 static PFN_Uniform1i uniform1i;
 static PFN_Uniform2i uniform2i;
 static PFN_Uniform3i uniform3i;
 static PFN_Uniform4i uniform4i;
 static PFN_UniformMatrix3fv uniformMatrix3fv;
 static PFN_UniformMatrix4fv uniformMatrix4fv;
 static PFN_GetAttribLocation getAttribLocation;
 static PFN_BindAttribLocation bindAttribLocation;
 static PFN_GenVertexArrays genVertexArrays;
 static PFN_BindVertexArray bindVertexArray;
 static PFN_DeleteVertexArrays deleteVertexArrays;
 static PFN_VertexAttribPointer vertexAttribPointer;
 static PFN_VertexAttribIPointer vertexAttribIPointer;
 static PFN_EnableVertexAttribArray enableVertexAttribArray;
 static PFN_DisableVertexAttribArray disableVertexAttribArray;
 static PFN_VertexAttrib4f vertexAttrib4f;
 static PFN_GenerateMipmap generateMipmap;
 static PFN_GetStringi getStringi;
 static PFN_BlitFramebuffer blitFramebuffer;
 static PFN_TexImage3D texImage3D;
 static PFN_GenQueries genQueries;
 static PFN_DeleteQueries deleteQueries;
 static PFN_BeginQuery beginQuery;
 static PFN_EndQuery endQuery;
 static PFN_GetQueryObjectiv getQueryObjectiv;
 static PFN_GetQueryObjectui64v getQueryObjectui64v;
 static PFN_QueryCounter queryCounter;
 static PFN_CopyImageSubData copyImageSubData;
 static PFN_DispatchCompute dispatchCompute;
 static PFN_DispatchComputeIndirect dispatchComputeIndirect;
 static PFN_MemoryBarrier memoryBarrier;
 static PFN_BindImageTexture bindImageTexture;
 static PFN_ClearTexImage clearTexImage;
 static PFN_BindBufferBase bindBufferBase;
 static PFN_GenSamplers genSamplers;
 static PFN_DeleteSamplers deleteSamplers;
 static PFN_BindSampler bindSampler;
 static PFN_SamplerParameteri samplerParameteri;
 static PFN_BlendFunci blendFunci;
 static PFN_BlendFuncSeparate blendFuncSeparate;
 static PFN_BlendFuncSeparatei blendFuncSeparatei;
 static void* activeTexture;
 static bool vboSupported;
 static bool framebufferSupported;
 static bool vaoSupported;
 static bool shaderSupported;
 static bool timerQuerySupported;
 static bool computeSupported;
 static bool instancedDrawSupported;
 static bool ssboSupported;
 static bool asyncReadbackSupported;
 static int maxShaderStorageUnits;
 static bool samplerObjectsSupported;
 static bool perBufferBlendingSupported;
 static bool swapControlTearSupported;
 static void init();
 static void ensureLoaded();
 // Driver swap-interval (0 / 1 / -1). Never applies interval >= 2.
 static void setSwapPacing(SwapPacing pacing);
 static void resetSwapPacingCache();
 static bool present();
};
} // namespace net::minecraft::client::gl
