# Generates EmbeddedGlslSnippets.cpp from src/.../shaders/glsl/*.glsl.
# Run with: cmake -DGLSL_DIR=<dir> -DOUTPUT=<path> -P tools/gen-embedded-glsl.cmake
cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED GLSL_DIR OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GLSL_DIR and OUTPUT must be defined")
endif()
file(GLOB GLSL_FILES "${GLSL_DIR}/*.glsl")
if(NOT GLSL_FILES)
    message(FATAL_ERROR "No .glsl files found in ${GLSL_DIR}")
endif()
list(SORT GLSL_FILES)
set(GEN "// Generated from ${GLSL_DIR}/*.glsl. Do not edit.\n")
string(APPEND GEN "#include <string>\n")
string(APPEND GEN "#include <unordered_map>\n")
string(APPEND GEN "#include \"net/minecraft/client/render/shaders/GlslSnippets.hpp\"\n")
string(APPEND GEN "namespace net::minecraft::client::render {\n")
string(APPEND GEN "const std::unordered_map<std::string, std::string>& GlslSnippets::embeddedGlslSnippets() {\n")
string(APPEND GEN " static const std::unordered_map<std::string, std::string> kSnippets = {\n")
foreach(glsl IN LISTS GLSL_FILES)
    get_filename_component(filename "${glsl}" NAME)
    string(REGEX REPLACE "\.glsl$" "" name "${filename}")
    file(READ "${glsl}" content)
    string(FIND "${content}" ")GLSL\"" hazard)
    if(NOT hazard EQUAL -1)
        message(FATAL_ERROR "GLSL snippet ${name} contains the raw-string terminator )GLSL\"")
    endif()
    string(APPEND GEN "  {\"${name}\", R\"GLSL(${content})GLSL\"},\n")
endforeach()
string(APPEND GEN " };\n")
string(APPEND GEN " return kSnippets;\n")
string(APPEND GEN "}\n")
string(APPEND GEN "} // namespace net::minecraft::client::render\n")
file(WRITE "${OUTPUT}" "${GEN}")
