# Generates EmbeddedVanillaPack.cpp from src/.../shaders/glsl/vanilla/** (the built-in
# vanilla shader pack). Each pack-relative path maps to the file text, keyed the same
# way PackLoader addresses resources ("shaders/gbuffers_terrain.vsh").
#
# Shader stages are baked pre-processed: #include lines are expanded recursively
# and // comments, trailing whitespace and blank lines are stripped, so the binary
# carries no pack-parse or include machinery at runtime. /* */ blocks survive —
# PackLoader reads render-target directives like /* RENDERTARGETS: 0 */ from them.
# Run with: cmake -DVANILLA_PACK_DIR=<dir> -DOUTPUT=<path> -P tools/gen-embedded-vanilla-pack.cmake
cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED VANILLA_PACK_DIR OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "VANILLA_PACK_DIR and OUTPUT must be defined")
endif()
file(GLOB_RECURSE PACK_FILES RELATIVE "${VANILLA_PACK_DIR}" "${VANILLA_PACK_DIR}/*")
set(REAL_FILES)
foreach(pack_file IN LISTS PACK_FILES)
    if(IS_DIRECTORY "${VANILLA_PACK_DIR}/${pack_file}")
        continue()
    endif()
    list(APPEND REAL_FILES "${pack_file}")
endforeach()
if(NOT REAL_FILES)
    message(FATAL_ERROR "No files found in ${VANILLA_PACK_DIR}")
endif()
list(SORT REAL_FILES)

function(normalize_pack_path out path)
    string(REPLACE "\\" "/" p "${path}")
    string(REGEX REPLACE "/{2,}" "/" p "${p}")
    string(REPLACE "/" ";" parts "${p}")
    set(stack)
    foreach(part IN LISTS parts)
        if(part STREQUAL "." OR part STREQUAL "")
            continue()
        elseif(part STREQUAL "..")
            if(stack)
                list(POP_BACK stack)
            endif()
        else()
            list(APPEND stack "${part}")
        endif()
    endforeach()
    string(JOIN "/" result ${stack})
    set(${out} "${result}" PARENT_SCOPE)
endfunction()

function(expand_file out path stack)
    if(path IN_LIST stack)
        message(FATAL_ERROR "Vanilla pack include cycle: ${path}")
    endif()
    list(APPEND stack "${path}")
    file(READ "${VANILLA_PACK_DIR}/${path}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(REPLACE "\r" "\n" content "${content}")
    set(result "")
    set(remaining "${content}")
    while(TRUE)
        string(FIND "${remaining}" "#include" inc_pos)
        if(inc_pos EQUAL -1)
            string(APPEND result "${remaining}")
            break()
        endif()
        string(SUBSTRING "${remaining}" 0 ${inc_pos} prefix)
        string(FIND "${prefix}" "\n" nl_pos)
        if(nl_pos EQUAL -1)
            set(prefix_ws "${prefix}")
        else()
            string(SUBSTRING "${prefix}" ${nl_pos} -1 prefix_ws)
        endif()
        if(NOT prefix_ws MATCHES "^\n?[ \t]*$")
            # "#include" inside a comment or string: keep the line verbatim.
            string(FIND "${remaining}" "\n" rest_nl)
            if(rest_nl EQUAL -1)
                string(APPEND result "${remaining}")
                set(remaining "")
            else()
                string(SUBSTRING "${remaining}" 0 ${rest_nl} line)
                math(EXPR after_nl "${rest_nl} + 1")
                string(SUBSTRING "${remaining}" ${after_nl} -1 remaining)
                string(APPEND result "${line}\n")
            endif()
            continue()
        endif()
        string(SUBSTRING "${remaining}" ${inc_pos} -1 rest)
        string(REGEX MATCH "^[ \t]*#include[ \t]*[\"<]([^\"<>]+)[\">]" inc_decl "${rest}")
        if(NOT inc_decl)
            message(FATAL_ERROR "Malformed #include in ${path}")
        endif()
        set(inc "${CMAKE_MATCH_1}")
        if(inc MATCHES "^/")
            string(SUBSTRING "${inc}" 1 -1 inc_rel)
            set(inc_path "shaders/${inc_rel}")
        else()
            get_filename_component(cur_dir "${path}" DIRECTORY)
            if(cur_dir STREQUAL "")
                set(inc_path "${inc}")
            else()
                set(inc_path "${cur_dir}/${inc}")
            endif()
        endif()
        normalize_pack_path(inc_path "${inc_path}")
        if(NOT EXISTS "${VANILLA_PACK_DIR}/${inc_path}")
            message(FATAL_ERROR "Vanilla pack #include \"${inc}\" from ${path} missing: ${inc_path}")
        endif()
        expand_file(inc_content "${inc_path}" "${stack}")
        string(APPEND result "${prefix}${inc_content}")
        string(FIND "${rest}" "\n" rest_nl)
        if(rest_nl EQUAL -1)
            set(remaining "")
        else()
            math(EXPR after_nl "${rest_nl} + 1")
            string(SUBSTRING "${rest}" ${after_nl} -1 remaining)
        endif()
    endwhile()
    set(${out} "${result}" PARENT_SCOPE)
endfunction()

function(minify_shader out text)
    string(REGEX REPLACE "//[^\n]*" "" text "${text}")
    set(result "")
    set(remaining "${text}")
    while(TRUE)
        string(FIND "${remaining}" "\n" nl_pos)
        if(nl_pos EQUAL -1)
            set(line "${remaining}")
            set(remaining "")
        else()
            string(SUBSTRING "${remaining}" 0 ${nl_pos} line)
            math(EXPR after_nl "${nl_pos} + 1")
            string(SUBSTRING "${remaining}" ${after_nl} -1 remaining)
        endif()
        string(REGEX REPLACE "[ \t]+$" "" line "${line}")
        if(NOT line STREQUAL "")
            string(APPEND result "${line}\n")
        endif()
        if(remaining STREQUAL "")
            break()
        endif()
    endwhile()
    set(${out} "${result}" PARENT_SCOPE)
endfunction()

set(GEN "// Generated from ${VANILLA_PACK_DIR}/**. Do not edit.\n")
string(APPEND GEN "#include <string>\n")
string(APPEND GEN "#include <unordered_map>\n")
string(APPEND GEN "#include \"net/minecraft/client/render/shaderpack/VanillaPackEmbed.hpp\"\n")
string(APPEND GEN "namespace net::minecraft::client::render {\n")
string(APPEND GEN "const std::unordered_map<std::string, std::string>& VanillaPackEmbed::embeddedResources() {\n")
string(APPEND GEN " static const std::unordered_map<std::string, std::string> kResources = {\n")
foreach(pack_file IN LISTS REAL_FILES)
    get_filename_component(ext "${pack_file}" EXT)
    if(ext STREQUAL ".vsh" OR ext STREQUAL ".fsh" OR ext STREQUAL ".gsh" OR
       ext STREQUAL ".csh" OR ext STREQUAL ".tcs" OR ext STREQUAL ".tes" OR ext STREQUAL ".glsl")
        set(content "${pack_file}")
        expand_file(content "${pack_file}" "")
        minify_shader(content "${content}")
    else()
        file(READ "${VANILLA_PACK_DIR}/${pack_file}" content)
        string(REPLACE "\r\n" "\n" content "${content}")
        string(REPLACE "\r" "\n" content "${content}")
    endif()
    string(FIND "${content}" ")GLSL\"" hazard)
    if(NOT hazard EQUAL -1)
        message(FATAL_ERROR "Vanilla pack file ${pack_file} contains the raw-string terminator )GLSL\"")
    endif()
    string(APPEND GEN "  {\"${pack_file}\", R\"GLSL(${content})GLSL\"},\n")
endforeach()
string(APPEND GEN " };\n")
string(APPEND GEN " return kResources;\n")
string(APPEND GEN "}\n")
string(APPEND GEN "} // namespace net::minecraft::client::render\n")
file(WRITE "${OUTPUT}" "${GEN}")
